In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset, drop_first = True).astype(int)

In [4]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent = dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler

In [13]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [18]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

param_grid = {    'criterion': ['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
    'splitter': ['best', 'random'],
     'max_features': [None, 'sqrt', 'log2']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3, n_jobs=1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV 1/5] END criterion=squared_error, max_features=None, splitter=best;, score=0.724 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=None, splitter=best;, score=0.553 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=None, splitter=best;, score=0.737 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=None, splitter=best;, score=0.558 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=None, splitter=best;, score=0.690 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=None, splitter=random;, score=0.741 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=None, splitter=random;, score=0.681 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=None, splitter=random;, score=0.740 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=None, splitter=random;, score=0.559 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=None, splitter=random;, score=0.673 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.654 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.560 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.613 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.602 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.644 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.704 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.483 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.579 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.408 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.622 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.722 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.560 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.534 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.570 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.647 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.673 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.571 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.603 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.614 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.662 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=None, splitter=best;, score=0.728 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=None, splitter=best;, score=0.543 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=None, splitter=best;, score=0.708 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=None, splitter=best;, score=0.587 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=None, splitter=best;, score=0.668 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=None, splitter=random;, score=0.685 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=None, splitter=random;, score=0.660 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=None, splitter=random;, score=0.746 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=None, splitter=random;, score=0.675 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=None, splitter=random;, score=0.558 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.654 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.515 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.724 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.537 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.677 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.630 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.615 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.643 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.596 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.633 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.602 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.400 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.742 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.678 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.536 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.566 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.572 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.650 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.538 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.617 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=None, splitter=best;, score=0.669 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=None, splitter=best;, score=0.589 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=None, splitter=best;, score=0.657 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=None, splitter=best;, score=0.590 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=None, splitter=best;, score=0.615 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=None, splitter=random;, score=0.677 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=None, splitter=random;, score=0.685 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=None, splitter=random;, score=0.683 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=None, splitter=random;, score=0.539 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=None, splitter=random;, score=0.698 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.647 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.491 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.453 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.657 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.538 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.717 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.633 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.637 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.598 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.639 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.629 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.532 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.713 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.631 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.637 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.644 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.607 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.647 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.648 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.643 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=None, splitter=best;, score=0.773 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=None, splitter=best;, score=0.533 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=None, splitter=best;, score=0.734 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=None, splitter=best;, score=0.584 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=None, splitter=best;, score=0.671 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=None, splitter=random;, score=0.717 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=None, splitter=random;, score=0.551 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=None, splitter=random;, score=0.697 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=None, splitter=random;, score=0.644 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=None, splitter=random;, score=0.664 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=sqrt, splitter=best;, score=0.728 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=sqrt, splitter=best;, score=0.446 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=sqrt, splitter=best;, score=0.694 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=sqrt, splitter=best;, score=0.533 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=sqrt, splitter=best;, score=0.523 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=sqrt, splitter=random;, score=0.654 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=sqrt, splitter=random;, score=0.579 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=sqrt, splitter=random;, score=0.518 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=sqrt, splitter=random;, score=0.515 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=sqrt, splitter=random;, score=0.556 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=log2, splitter=best;, score=0.668 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=log2, splitter=best;, score=0.549 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=log2, splitter=best;, score=0.718 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=log2, splitter=best;, score=0.455 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=log2, splitter=best;, score=0.618 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=log2, splitter=random;, score=0.630 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=log2, splitter=random;, score=0.492 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=log2, splitter=random;, score=0.583 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=log2, splitter=random;, score=0.661 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=log2, splitter=random;, score=0.566 total time=   0.0s

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [19]:
print("The R score value for the best parameter {}".format(grid.best_params_))

The R score value for the best parameter {'criterion': 'squared_error', 'max_features': None, 'splitter': 'random'}

In [20]:
re = grid.cv_results_

In [21]:
table = pd.DataFrame.from_dict(re)

In [22]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007252,0.005285,0.003948,5.630822e-03,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.724449,0.552571,0.736871,0.558402,0.690101,0.652479,0.080683,6
1,0.001248,0.002495,0.007050,7.500366e-03,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.740512,0.681497,0.739961,0.558615,0.672963,0.678710,0.066385,1
2,0.004417,0.000402,0.001974,6.641619e-04,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.654254,0.560374,0.613337,0.601921,0.644073,0.614792,0.033298,15
3,0.001795,0.000399,0.001138,4.432673e-04,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.703718,0.482991,0.579357,0.408147,0.621624,0.559167,0.103743,23
4,0.001115,0.001372,0.000199,3.989220e-04,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.722125,0.559761,0.533794,0.569732,0.646739,0.606430,0.069009,16
5,0.003125,0.006251,0.000000,0.000000e+00,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.672652,0.570657,0.603207,0.614082,0.661949,0.624509,0.037900,11
6,0.003929,0.006050,0.003523,6.097656e-03,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.728113,0.542597,0.708038,0.587022,0.668058,0.646766,0.071057,7
7,0.003234,0.004791,0.000216,2.646538e-04,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.684926,0.659567,0.745836,0.675332,0.558319,0.664796,0.060743,2
8,0.004825,0.004222,0.001989,6.348384e-04,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.654464,0.514954,0.723659,0.537223,0.676955,0.621451,0.081306,14
9,0.002541,0.000459,0.001197,3.989461e-04,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.630371,0.615371,0.642773,0.596070,0.633289,0.623575,0.016327,13
10,0.002194,0.000399,0.000997,1.507891e-07,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.601875,0.400431,0.742280,0.677654,0.535782,0.591604,0.118217,18
11,0.000899,0.001112,0.000199,3.985405e-04,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.566272,0.572405,0.649663,0.538214,0.616919,0.588695,0.039573,19
12,0.012498,0.006249,0.003124,6.248474e-03,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.669302,0.589120,0.656790,0.590281,0.614823,0.624063,0.033362,12
13,0.008026,0.006864,0.003125,6.249237e-03,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.676671,0.684756,0.683151,0.539468,0.698119,0.656433,0.058897,4
14,0.008734,0.006770,0.000998,6.309773e-04,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.647351,0.490895,0.453350,0.656903,0.537509,0.557201,0.082020,24
15,0.006659,0.007370,0.000000,0.000000e+00,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.717348,0.633290,0.636974,0.598162,0.639017,0.644958,0.039154,8
16,0.006242,0.007645,0.003124,6.247616e-03,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.629198,0.531607,0.713186,0.630619,0.637298,0.628382,0.057693,10
17,0.006249,0.007653,0.000000,0.000000e+00,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.644033,0.606886,0.647115,0.647987,0.642682,0.637740,0.015549,9
18,0.000000,0.000000,0.000000,0.000000e+00,poisson,None,best,"{'criterion': 'poisson', 'max_features': None,...",0.772897,0.533384,0.733800,0.584322,0.671094,0.659100,0.089521,3
19,0.004430,0.007340,0.003426,6.364379e-03,poisson,None,random,"{'criterion': 'poisson', 'max_features': None,...",0.717171,0.550919,0.697078,0.644268,0.664219,0.654731,0.057738,5
20,0.001197,0.001466,0.003730,6.008666e-03,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.728228,0.445555,0.693605,0.533095,0.522767,0.584650,0.108001,21
21,0.002002,0.000015,0.001196,4.009517e-04,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.653940,0.579099,0.518353,0.514728,0.555976,0.564419,0.050778,22
22,0.001201,0.001471,0.000200,3.990173e-04,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.667562,0.549003,0.717901,0.454855,0.617733,0.601411,0.092127,17
23,0.003132,0.006264,0.003117,6.233597e-03,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.630285,0.491530,0.582659,0.660804,0.565646,0.586185,0.058149,20

In [23]:
age_input=float(input("Age=:"))
bmi_input=float(input("BMI=:"))
children_input=float(input("Children=:"))
sex_male_input=int(input("Sex=:"))
smoker_yes_input=int(input("Smoker=:"))

Age=: 33
BMI=: 24
Children=: 2
Sex=: 1
Smoker=: 0

In [24]:
future_prediction = grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future Prediction ={}".format(future_prediction))

Future Prediction =[15555.]