In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset, drop_first = True).astype(int)

In [4]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent = dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

param_grid = {    'criterion': ['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
    'splitter': ['best', 'random'],
     'max_features': [None, 'sqrt', 'log2']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3, n_jobs=1)
grid.fit(independent, dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV 1/5] END criterion=squared_error, max_features=None, splitter=best;, score=0.754 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=None, splitter=best;, score=0.683 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=None, splitter=best;, score=0.746 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=None, splitter=best;, score=0.700 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=None, splitter=best;, score=0.676 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=None, splitter=random;, score=0.725 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=None, splitter=random;, score=0.616 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=None, splitter=random;, score=0.761 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=None, splitter=random;, score=0.719 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=None, splitter=random;, score=0.745 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.769 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.568 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.726 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.710 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=sqrt, splitter=best;, score=0.671 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.715 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.561 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.731 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.687 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=sqrt, splitter=random;, score=0.731 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.692 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.614 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.672 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.710 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=log2, splitter=best;, score=0.700 total time=   0.0s
[CV 1/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.708 total time=   0.0s
[CV 2/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.577 total time=   0.0s
[CV 3/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.703 total time=   0.0s
[CV 4/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.722 total time=   0.0s
[CV 5/5] END criterion=squared_error, max_features=log2, splitter=random;, score=0.670 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=None, splitter=best;, score=0.760 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=None, splitter=best;, score=0.642 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=None, splitter=best;, score=0.719 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=None, splitter=best;, score=0.712 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=None, splitter=best;, score=0.688 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=None, splitter=random;, score=0.650 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=None, splitter=random;, score=0.537 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=None, splitter=random;, score=0.669 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=None, splitter=random;, score=0.721 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=None, splitter=random;, score=0.725 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.712 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.500 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.671 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.670 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.559 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.642 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.590 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.666 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.725 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.711 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.703 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.607 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.743 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.708 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.696 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.712 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.552 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.766 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.654 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.625 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=None, splitter=best;, score=0.688 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=None, splitter=best;, score=0.690 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=None, splitter=best;, score=0.727 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=None, splitter=best;, score=0.714 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=None, splitter=best;, score=0.719 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=None, splitter=random;, score=0.695 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=None, splitter=random;, score=0.626 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=None, splitter=random;, score=0.736 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=None, splitter=random;, score=0.760 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=None, splitter=random;, score=0.715 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.700 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.551 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.612 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.639 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, splitter=best;, score=0.717 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.679 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.386 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.722 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.670 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=sqrt, splitter=random;, score=0.727 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.585 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.627 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.607 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.715 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=log2, splitter=best;, score=0.740 total time=   0.0s
[CV 1/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.722 total time=   0.0s
[CV 2/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.492 total time=   0.0s
[CV 3/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.633 total time=   0.0s
[CV 4/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.661 total time=   0.0s
[CV 5/5] END criterion=absolute_error, max_features=log2, splitter=random;, score=0.676 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=None, splitter=best;, score=0.745 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=None, splitter=best;, score=0.644 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=None, splitter=best;, score=0.732 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=None, splitter=best;, score=0.681 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=None, splitter=best;, score=0.724 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=None, splitter=random;, score=0.673 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=None, splitter=random;, score=0.673 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=None, splitter=random;, score=0.702 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=None, splitter=random;, score=0.704 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=None, splitter=random;, score=0.727 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=sqrt, splitter=best;, score=0.621 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=sqrt, splitter=best;, score=0.602 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=sqrt, splitter=best;, score=0.786 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=sqrt, splitter=best;, score=0.729 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=sqrt, splitter=best;, score=0.691 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=sqrt, splitter=random;, score=0.694 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=sqrt, splitter=random;, score=0.502 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=sqrt, splitter=random;, score=0.592 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=sqrt, splitter=random;, score=0.710 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=sqrt, splitter=random;, score=0.541 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=log2, splitter=best;, score=0.721 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=log2, splitter=best;, score=0.664 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=log2, splitter=best;, score=0.650 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=log2, splitter=best;, score=0.710 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=log2, splitter=best;, score=0.647 total time=   0.0s
[CV 1/5] END criterion=poisson, max_features=log2, splitter=random;, score=0.629 total time=   0.0s
[CV 2/5] END criterion=poisson, max_features=log2, splitter=random;, score=0.493 total time=   0.0s
[CV 3/5] END criterion=poisson, max_features=log2, splitter=random;, score=0.596 total time=   0.0s
[CV 4/5] END criterion=poisson, max_features=log2, splitter=random;, score=0.660 total time=   0.0s
[CV 5/5] END criterion=poisson, max_features=log2, splitter=random;, score=0.658 total time=   0.0s

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [9]:
print("The R score value for the best parameter {}".format(grid.best_params_))

The R score value for the best parameter {'criterion': 'squared_error', 'max_features': None, 'splitter': 'random'}

In [10]:
re = grid.cv_results_

In [11]:
table = pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006255,0.007661,0.000000,0.000000,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.754031,0.683327,0.745666,0.699945,0.676388,0.711871,0.032049,2
1,0.009366,0.007647,0.000000,0.000000,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.725142,0.616058,0.761304,0.719255,0.744570,0.713266,0.050821,1
2,0.006249,0.007653,0.000000,0.000000,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.769355,0.567544,0.725741,0.710320,0.670669,0.688726,0.068336,9
3,0.000000,0.000000,0.003130,0.006261,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.715157,0.560532,0.731115,0.686584,0.731365,0.684951,0.064313,11
4,0.006248,0.007652,0.000000,0.000000,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.692385,0.614045,0.672039,0.710226,0.700228,0.677785,0.034249,13
5,0.005334,0.005485,0.005291,0.005036,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.707752,0.576616,0.703010,0.722123,0.669549,0.675810,0.052505,14
6,0.004001,0.002097,0.000798,0.000747,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.760385,0.641901,0.718765,0.712303,0.687632,0.704197,0.038962,6
7,0.007129,0.005285,0.002249,0.000387,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.650364,0.536743,0.669426,0.720520,0.725045,0.660420,0.068215,17
8,0.003125,0.006249,0.000000,0.000000,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.711589,0.499876,0.671121,0.670291,0.559455,0.622466,0.079494,22
9,0.006248,0.007653,0.000000,0.000000,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.642319,0.589834,0.665780,0.725347,0.711082,0.666872,0.048811,15
10,0.003132,0.006263,0.003117,0.006234,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.702745,0.607321,0.742979,0.708483,0.695969,0.691499,0.045102,8
11,0.006985,0.007021,0.000639,0.001278,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.712244,0.552146,0.766499,0.654421,0.624512,0.661964,0.073451,16
12,0.025357,0.007975,0.000404,0.000808,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.687775,0.690398,0.727324,0.713614,0.719359,0.707694,0.015826,3
13,0.022172,0.005205,0.001767,0.001005,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.695218,0.625968,0.736396,0.759501,0.714503,0.706317,0.045562,4
14,0.021877,0.007644,0.000000,0.000000,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.700145,0.551180,0.611941,0.638539,0.716736,0.643708,0.060192,19
15,0.013899,0.009276,0.003519,0.006099,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.679191,0.385513,0.721741,0.670252,0.726857,0.636711,0.127582,20
16,0.015867,0.000491,0.000609,0.001218,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.584717,0.627135,0.607092,0.715323,0.739506,0.654755,0.061305,18
17,0.016681,0.008754,0.000584,0.001167,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.721878,0.491951,0.632855,0.660712,0.675950,0.636669,0.077897,21
18,0.005185,0.002779,0.004389,0.005794,poisson,None,best,"{'criterion': 'poisson', 'max_features': None,...",0.744991,0.644225,0.731943,0.681159,0.724290,0.705322,0.037306,5
19,0.006249,0.007654,0.000000,0.000000,poisson,None,random,"{'criterion': 'poisson', 'max_features': None,...",0.673303,0.673086,0.702291,0.703519,0.726869,0.695813,0.020440,7
20,0.006256,0.007662,0.000000,0.000000,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.621106,0.602482,0.785968,0.729327,0.690528,0.685882,0.067938,10
21,0.009373,0.007653,0.000000,0.000000,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.693615,0.502476,0.591904,0.709792,0.541182,0.607794,0.081915,23
22,0.004640,0.006217,0.003901,0.006050,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.720976,0.663730,0.650009,0.709614,0.646693,0.678205,0.031027,12
23,0.006678,0.007303,0.000798,0.000977,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.628546,0.493241,0.596429,0.659724,0.658027,0.607193,0.061482,24

In [13]:
age_input=float(input("Age=:"))
bmi_input=float(input("BMI=:"))
children_input=float(input("Children=:"))
sex_male_input=int(input("Sex=:"))
smoker_yes_input=int(input("Smoker=:"))

Age=: 33
BMI=: 24
Children=: 2
Sex=: 1
Smoker=: 0

In [14]:
future_prediction = grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future Prediction ={}".format(future_prediction))

Future Prediction =[5257.]

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(